spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
server:
  port: 8081
  servlet:
    context-path: /

springdoc:
  packages-to-scan: cn.yctech.facelogin.controller
